### ISSUE TITLE
QNH defined

### ISSUE THREAD

**Issue by John-Matty** [pimoroni/enviro-phat#27]
Am I missing something here - I am at a loss to understand why you have defined QNH as 1020 hPa when the ISO standard atmosphere has 1013.25 hPa as the average pressure at msl at 15 degrees C.
Sure you can provide the local QNH if known, but if you use the default 1020 hPa your altitude will be off by around 61.5 m or 202 feet. Explain please.

**Comment by John-Matty** [comment]
Oops, finger trouble....
Am I missing something here - I am at a loss to understand why you have defined QNH as 1020 hPa when the ISO standard atmosphere  has 1013.25 hPa as the average pressure at msl at 15 degrees C.
Sure you can provide the local QNH if known, but if you use the default 1020 hPa your altitude will be off by around 61.5 m or 202 feet. Explain please.

**Comment by Gadgetoid** [comment]
I can't recall where the 1020 value came from, I suspect it was the value for Sheffield, UK at time-of-writing.

My concern is that for anyone simply assuming altitude to "just work" and not supplying a regional QNH value, the ISO/ISA standard is still going to result in an incorrect local altitude.

It seems like the only sensible approach is to make QNH a *required* parameter, and store the standard value as something like "ISO_SEA_LEVEL = 1013.25" so the user has to make a conscious choice to supply their own, or use a standard value. This constitutes a breaking change to the API though, which is somewhat controversial and in a similar vein to: #25

Perhaps if these two changes were batched into a version 1.0.0 (since the major version number tends to indicate significant/potentially breaking changes) we could better justify the shift.

**Comment by John-Matty** [comment]
Hi
Thanks for your reply. I agree that it only really works if you input your local  pressure corrected to msg but my concern is that it is more relevant to have a recongnised pressure than some arbitrary value. According to the Met office, the lowest pressure on record in the UK is something like 928 hPa and the highest 1059 hPa(!) so your figure is not a million miles away. Thanks for the explanation. I am enjoying fiddling with the Pi and envirophat. I have had to learn Python from scratch having retired from computing 15 years ago. My inclinantion would be to use C or C++ except that the standard libraries have changed so much, I have found it easier to use Python!
Cheers,
John Matty

**Comment by Gadgetoid** [comment]
I agree, the default should be something sensible- I think with the other changes in the pipeline for Enviro pHAT warranting a bump to 1.0.0 I'm going to make and document this change, and deal with the consequences. That's what I keep those major version numbers around for ;)
